# Generated by Django 3.1.2 on 2021-01-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightsafetyreport',
            old_name='contact',
            new_name='contact_email',
        ),
        migrations.AddField(
            model_name='flightsafetyreport',
            name='contact_number',
            field=models.CharField(default='123456789', max_length=100),
            preserve_default=False,
        ),
    ]
